const STATES = {
    michigan: {
        name: 'Michigan',
        template_id: 980,
        api_url: 'https://veriftools.bz/michigan-driver-license-version-1/',
        fields: [
            { name: 'last_name', label: 'Last Name', required: true },
            { name: 'first_name', label: 'First Name', required: true },
            { name: 'license_number', label: 'License Number', required: true },
            { name: 'address_street', label: 'Street Address', required: true },
            { name: 'address_city', label: 'City', required: true },
            { name: 'address_state', label: 'State', required: true },
            { name: 'address_zip', label: 'ZIP Code', required: true },
            { name: 'date_of_birth', label: 'Date of Birth', type: 'date', required: true },
            { name: 'issue_date', label: 'Issue Date', type: 'date', required: true },
            { name: 'expire_date', label: 'Expiration Date', type: 'date', required: true },
            { name: 'sex', label: 'Sex', type: 'select', options: ['M', 'F'], required: true },
            { name: 'height', label: 'Height', placeholder: "5'-09\"" },
            { name: 'eyes', label: 'Eye Color', placeholder: 'BRN' },
            { name: 'dl_class', label: 'Class', placeholder: 'D' },
            { name: 'endorsements', label: 'Endorsements', placeholder: 'NONE' },
            { name: 'restrictions', label: 'Restrictions', placeholder: 'NONE' },
            { name: 'dd_code', label: 'DD Code' },
            { name: 'back_inventory_serial', label: 'Back Inventory Serial' },
            { name: 'revision_date', label: 'Revision Date', type: 'date' },
            { name: 'initials_year_code', label: 'Initials Year Code' }
        ],
        buildPayload: (data, photoBase64, apiKey) => ({
            api_key: apiKey,
            template_id: 980,
            output_style: "photo",
            data: {
                last_name: data.last_name || '',
                first_name: data.first_name || '',
                license_number: data.license_number || '',
                address_street: data.address_street || '',
                address_city: data.address_city || '',
                address_state: data.address_state || '',
                address_zip: data.address_zip || '',
                date_of_birth: data.date_of_birth || '',
                issue_date: data.issue_date || '',
                expire_date: data.expire_date || '',
                sex: data.sex || '',
                height: data.height || '',
                eyes: data.eyes || '',
                dl_class: data.dl_class || '',
                endorsements: data.endorsements || '',
                restrictions: data.restrictions || '',
                dd_code: data.dd_code || '',
                back_inventory_serial: data.back_inventory_serial || '',
                date_of_birth: data.date_of_birth || '',
                revision_date: data.revision_date || '',
                date_of_birth: data.date_of_birth || '',
                initials_year_code: data.initials_year_code || '',
                main_photo: photoBase64,
                main_photo: photoBase64
            }
        })
    },

    pennsylvania: {
        name: 'Pennsylvania',
        template_id: 1029,
        api_url: 'https://veriftools.bz/pennsylvania-driver-version-1/',
        fields: [
            { name: 'last_name', label: 'Last Name', required: true },
            { name: 'first_middle_name', label: 'First & Middle Name', required: true },
            { name: 'address_street', label: 'Street Address', required: true },
            { name: 'address_city', label: 'City', required: true },
            { name: 'address_state', label: 'State', required: true },
            { name: 'address_zip', label: 'ZIP Code', required: true },
            { name: 'date_of_birth', label: 'Date of Birth', type: 'date', required: true },
            { name: 'issue_date', label: 'Issue Date', type: 'date', required: true },
            { name: 'expire_date', label: 'Expiration Date', type: 'date', required: true },
            { name: 'license_number', label: 'License Number', required: true },
            { name: 'dups_number', label: 'DUPS Number' },
            { name: 'dl_class', label: 'Class', placeholder: 'C' },
            { name: 'endorsements', label: 'Endorsements', placeholder: 'NONE' },
            { name: 'restrictions', label: 'Restrictions', placeholder: 'NONE' },
            { name: 'sex', label: 'Sex', type: 'select', options: ['M', 'F'], required: true },
            { name: 'height', label: 'Height', placeholder: "5'-09\"" },
            { name: 'eyes', label: 'Eye Color', placeholder: 'BRN' },
            { name: 'dd_code', label: 'DD Code' },
            { name: 'revision_date', label: 'Revision Date', type: 'date' },
            { name: 'back_end_desc', label: 'Back Endorsements Description' },
            { name: 'back_restr_desc', label: 'Back Restrictions Description' },
            { name: 'photo_center_code', label: 'Photo Center Code' },
            { name: 'back_inventory_serial', label: 'Back Inventory Serial' }
        ],
        buildPayload: (data, photoBase64, apiKey) => ({
            api_key: apiKey,
            template_id: 1029,
            output_style: "photo",
            data: {
                last_name: data.last_name || '',
                first_middle_name: data.first_middle_name || '',
                address_street: data.address_street || '',
                address_city: data.address_city || '',
                address_state: data.address_state || '',
                address_zip: data.address_zip || '',
                date_of_birth: data.date_of_birth || '',
                issue_date: data.issue_date || '',
                expire_date: data.expire_date || '',
                license_number: data.license_number || '',
                dups_number: data.dups_number || '',
                dl_class: data.dl_class || '',
                endorsements: data.endorsements || '',
                restrictions: data.restrictions || '',
                sex: data.sex || '',
                height: data.height || '',
                eyes: data.eyes || '',
                dd_code: data.dd_code || '',
                revision_date: data.revision_date || '',
                date_of_birth: data.date_of_birth || '',
                back_end_desc: data.back_end_desc || '',
                back_restr_desc: data.back_restr_desc || '',
                photo_center_code: data.photo_center_code || '',
                back_inventory_serial: data.back_inventory_serial || '',
                main_photo: photoBase64,
                main_photo: photoBase64
            }
        })
    },

    washington: {
        name: 'Washington',
        template_id: 1009,
        api_url: 'https://veriftools.bz/washington-driver-license-version-1/',
        fields: [
            { name: 'last_name', label: 'Last Name', required: true },
            { name: 'first_name', label: 'First Name', required: true },
            { name: 'license_number', label: 'License Number', required: true },
            { name: 'address_street', label: 'Street Address', required: true },
            { name: 'address_city', label: 'City', required: true },
            { name: 'address_state', label: 'State', required: true },
            { name: 'address_zip', label: 'ZIP Code', required: true },
            { name: 'date_of_birth', label: 'Date of Birth', type: 'date', required: true },
            { name: 'issue_date', label: 'Issue Date', type: 'date', required: true },
            { name: 'expire_date', label: 'Expiration Date', type: 'date', required: true },
            { name: 'sex', label: 'Sex', type: 'select', options: ['M', 'F'], required: true },
            { name: 'height', label: 'Height', placeholder: "5'-09\"" },
            { name: 'weight', label: 'Weight', placeholder: '150' },
            { name: 'eyes', label: 'Eye Color', placeholder: 'BRN' },
            { name: 'dl_class', label: 'Class', placeholder: 'D' },
            { name: 'endorsements', label: 'Endorsements', placeholder: 'NONE' },
            { name: 'restrictions', label: 'Restrictions', placeholder: 'NONE' },
            { name: 'vertical_serial', label: 'Vertical Serial' },
            { name: 'dd_code', label: 'DD Code' },
            { name: 'revision_date', label: 'Revision Date', type: 'date' }
        ],
        buildPayload: (data, photoBase64, apiKey) => ({
            api_key: apiKey,
            template_id: 1009,
            output_style: "photo",
            data: {
                last_name: data.last_name || '',
                first_name: data.first_name || '',
                license_number: data.license_number || '',
                address_street: data.address_street || '',
                address_city: data.address_city || '',
                address_state: data.address_state || '',
                address_zip: data.address_zip || '',
                date_of_birth: data.date_of_birth || '',
                issue_date: data.issue_date || '',
                expire_date: data.expire_date || '',
                sex: data.sex || '',
                height: data.height || '',
                weight: data.weight || '',
                eyes: data.eyes || '',
                dl_class: data.dl_class || '',
                endorsements: data.endorsements || '',
                restrictions: data.restrictions || '',
                vertical_serial: data.vertical_serial || '',
                dd_code: data.dd_code || '',
                vertical_serial: data.vertical_serial || '',
                endorsements: data.endorsements || '',
                restrictions: data.restrictions || '',
                date_of_birth: data.date_of_birth || '',
                revision_date: data.revision_date || '',
                main_photo: photoBase64,
                main_photo: photoBase64
            }
        })
    },

    texas: {
        name: 'Texas',
        template_id: 967,
        api_url: 'https://veriftools.bz/texas-driver-license-version-1/',
        fields: [
            { name: 'last_name', label: 'Last Name', required: true },
            { name: 'first_name', label: 'First Name', required: true },
            { name: 'license_number', label: 'License Number', required: true },
            { name: 'address_street', label: 'Street Address', required: true },
            { name: 'address_city', label: 'City', required: true },
            { name: 'address_state', label: 'State', required: true },
            { name: 'address_zip', label: 'ZIP Code', required: true },
            { name: 'date_of_birth', label: 'Date of Birth', type: 'date', required: true },
            { name: 'issue_date', label: 'Issue Date', type: 'date', required: true },
            { name: 'expire_date', label: 'Expiration Date', type: 'date', required: true },
            { name: 'dd_code', label: 'DD Code' },
            { name: 'sex', label: 'Sex', type: 'select', options: ['M', 'F'], required: true },
            { name: 'height', label: 'Height', placeholder: "5'-09\"" },
            { name: 'eyes', label: 'Eye Color', placeholder: 'BRN' },
            { name: 'dl_class', label: 'Class', placeholder: 'C' },
            { name: 'restrictions', label: 'Restrictions', placeholder: 'NONE' },
            { name: 'endorsements', label: 'Endorsements', placeholder: 'NONE' },
            { name: 'back_vertical_serial', label: 'Back Vertical Serial' },
            { name: 'revision_date', label: 'Revision Date', type: 'date' }
        ],
        buildPayload: (data, photoBase64, apiKey) => ({
            api_key: apiKey,
            template_id: 967,
            output_style: "photo",
            data: {
                last_name: data.last_name || '',
                first_name: data.first_name || '',
                license_number: data.license_number || '',
                address_street: data.address_street || '',
                address_city: data.address_city || '',
                address_state: data.address_state || '',
                address_zip: data.address_zip || '',
                date_of_birth: data.date_of_birth || '',
                date_of_birth: data.date_of_birth || '',
                issue_date: data.issue_date || '',
                expire_date: data.expire_date || '',
                dd_code: data.dd_code || '',
                sex: data.sex || '',
                height: data.height || '',
                eyes: data.eyes || '',
                dl_class: data.dl_class || '',
                restrictions: data.restrictions || '',
                endorsements: data.endorsements || '',
                back_vertical_serial: data.back_vertical_serial || '',
                revision_date: data.revision_date || '',
                date_of_birth: data.date_of_birth || '',
                main_photo: photoBase64,
                main_photo: photoBase64
            }
        })
    },

    newyork: {
        name: 'New York',
        template_id: 870,
        api_url: 'https://veriftools.bz/new-york-driver-license-version-1/',
        fields: [
            { name: 'first_name', label: 'First Name', required: true },
            { name: 'last_name', label: 'Last Name', required: true },
            { name: 'license_number', label: 'License Number', required: true },
            { name: 'address_street', label: 'Street Address', required: true },
            { name: 'address_city', label: 'City', required: true },
            { name: 'address_state', label: 'State', required: true },
            { name: 'address_zip', label: 'ZIP Code', required: true },
            { name: 'date_of_birth', label: 'Date of Birth', type: 'date', required: true },
            { name: 'issue_date', label: 'Issue Date', type: 'date', required: true },
            { name: 'expire_date', label: 'Expiration Date', type: 'date', required: true },
            { name: 'sex', label: 'Sex', type: 'select', options: ['M', 'F'], required: true },
            { name: 'height', label: 'Height', placeholder: "5'-09\"" },
            { name: 'eyes', label: 'Eye Color', placeholder: 'BRN' },
            { name: 'dl_class', label: 'Class', placeholder: 'D' },
            { name: 'restrictions', label: 'Restrictions', placeholder: 'NONE' },
            { name: 'endorsements', label: 'Endorsements', placeholder: 'NONE' },
            { name: 'front_inventory_number', label: 'Front Inventory Number' },
            { name: 'document_number', label: 'Document Number' },
            { name: 'back_serial_number', label: 'Back Serial Number' }
        ],
        buildPayload: (data, photoBase64, apiKey) => ({
            api_key: apiKey,
            template_id: 870,
            output_style: "photo",
            data: {
                first_name: data.first_name || '',
                last_name: data.last_name || '',
                license_number: data.license_number || '',
                address_street: data.address_street || '',
                address_city: data.address_city || '',
                address_state: data.address_state || '',
                address_zip: data.address_zip || '',
                date_of_birth: data.date_of_birth || '',
                date_of_birth: data.date_of_birth || '',
                issue_date: data.issue_date || '',
                expire_date: data.expire_date || '',
                sex: data.sex || '',
                height: data.height || '',
                eyes: data.eyes || '',
                dl_class: data.dl_class || '',
                restrictions: data.restrictions || '',
                endorsements: data.endorsements || '',
                front_inventory_number: data.front_inventory_number || '',
                document_number: data.document_number || '',
                back_serial_number: data.back_serial_number || '',
                main_photo: photoBase64,
                main_photo: photoBase64,
                main_photo: photoBase64
            }
        })
    },

    california: {
        name: 'California',
        template_id: 927,
        api_url: 'https://veriftools.bz/california-driver-license-version-1/',
        fields: [
            { name: 'first_name', label: 'First Name', required: true },
            { name: 'last_name', label: 'Last Name', required: true },
            { name: 'id_number', label: 'ID Number', required: true },
            { name: 'address_street', label: 'Street Address', required: true },
            { name: 'address_city', label: 'City', required: true },
            { name: 'address_state', label: 'State', required: true },
            { name: 'address_zip', label: 'ZIP Code', required: true },
            { name: 'date_of_birth', label: 'Date of Birth', type: 'date', required: true },
            { name: 'issue_date', label: 'Issue Date', type: 'date', required: true },
            { name: 'expire_date', label: 'Expiration Date', type: 'date', required: true },
            { name: 'sex', label: 'Sex', type: 'select', options: ['M', 'F'], required: true },
            { name: 'hair_color', label: 'Hair Color', placeholder: 'BRN' },
            { name: 'eyes', label: 'Eye Color', placeholder: 'BRN' },
            { name: 'height', label: 'Height', placeholder: "5'-09\"" },
            { name: 'weight', label: 'Weight', placeholder: '150' },
            { name: 'dd_code', label: 'DD Code' },
            { name: 'back_bottom_serial', label: 'Back Bottom Serial' },
            { name: 'revision_date', label: 'Revision Date', type: 'date' },
            { name: 'dl_class', label: 'Class', placeholder: 'C' },
            { name: 'endorsements', label: 'Endorsements', placeholder: 'NONE' },
            { name: 'security_text', label: 'Security Text' }
        ],
        buildPayload: (data, photoBase64, apiKey) => ({
            api_key: apiKey,
            template_id: 927,
            output_style: "photo",
            data: {
                first_name: data.first_name || '',
                last_name: data.last_name || '',
                id_number: data.id_number || '',
                address_street: data.address_street || '',
                address_city: data.address_city || '',
                address_state: data.address_state || '',
                address_zip: data.address_zip || '',
                date_of_birth: data.date_of_birth || '',
                issue_date: data.issue_date || '',
                expire_date: data.expire_date || '',
                sex: data.sex || '',
                hair_color: data.hair_color || '',
                eyes: data.eyes || '',
                height: data.height || '',
                weight: data.weight || '',
                dd_code: data.dd_code || '',
                date_of_birth: data.date_of_birth || '',
                back_bottom_serial: data.back_bottom_serial || '',
                revision_date: data.revision_date || '',
                date_of_birth: data.date_of_birth || '',
                dl_class: data.dl_class || '',
                endorsements: data.endorsements || '',
                security_text: data.security_text || '',
                security_text: data.security_text || '',
                security_text: data.security_text || '',
                main_photo: photoBase64,
                main_photo: photoBase64
            }
        })
    },

    virginia: {
        name: 'Virginia',
        template_id: 841,
        api_url: 'https://veriftools.bz/virginia-driver-license-version-1/',
        fields: [
            { name: 'first_name', label: 'First Name', required: true },
            { name: 'last_name', label: 'Last Name', required: true },
            { name: 'license_number', label: 'License Number', required: true },
            { name: 'address_street', label: 'Street Address', required: true },
            { name: 'address_city', label: 'City', required: true },
            { name: 'address_state', label: 'State', required: true },
            { name: 'address_zip', label: 'ZIP Code', required: true },
            { name: 'date_of_birth', label: 'Date of Birth', type: 'date', required: true },
            { name: 'issue_date', label: 'Issue Date', type: 'date', required: true },
            { name: 'expire_date', label: 'Expiration Date', type: 'date', required: true },
            { name: 'sex', label: 'Sex', type: 'select', options: ['M', 'F'], required: true },
            { name: 'height', label: 'Height', placeholder: "5'-09\"" },
            { name: 'eyes', label: 'Eye Color', placeholder: 'BRN' },
            { name: 'dl_class', label: 'Class', placeholder: 'D' },
            { name: 'endorsements', label: 'Endorsements', placeholder: 'NONE' },
            { name: 'restrictions', label: 'Restrictions', placeholder: 'NONE' },
            { name: 'dd_code', label: 'DD Code' },
            { name: 'back_serial_number', label: 'Back Serial Number' },
            { name: 'court_code', label: 'Court Code' }
        ],
        buildPayload: (data, photoBase64, apiKey) => ({
            api_key: apiKey,
            template_id: 841,
            output_style: "photo",
            data: {
                first_name: data.first_name || '',
                last_name: data.last_name || '',
                license_number: data.license_number || '',
                address_street: data.address_street || '',
                address_city: data.address_city || '',
                address_state: data.address_state || '',
                address_zip: data.address_zip || '',
                date_of_birth: data.date_of_birth || '',
                issue_date: data.issue_date || '',
                expire_date: data.expire_date || '',
                sex: data.sex || '',
                height: data.height || '',
                eyes: data.eyes || '',
                dl_class: data.dl_class || '',
                endorsements: data.endorsements || '',
                restrictions: data.restrictions || '',
                dd_code: data.dd_code || '',
                back_serial_number: data.back_serial_number || '',
                court_code: data.court_code || '',
                main_photo: photoBase64,
                main_photo: photoBase64,
                main_photo: photoBase64
            }
        })
    },

    florida: {
        name: 'Florida',
        template_id: 914,
        api_url: 'https://veriftools.bz/florida-driver-license-version-1/',
        fields: [
            { name: 'first_name', label: 'First Name', required: true },
            { name: 'last_name', label: 'Last Name', required: true },
            { name: 'license_number', label: 'License Number', required: true },
            { name: 'address_street', label: 'Street Address', required: true },
            { name: 'address_city', label: 'City', required: true },
            { name: 'address_state', label: 'State', required: true },
            { name: 'address_zip', label: 'ZIP Code', required: true },
            { name: 'date_of_birth', label: 'Date of Birth', type: 'date', required: true },
            { name: 'issue_date', label: 'Issue Date', type: 'date', required: true },
            { name: 'expire_date', label: 'Expiration Date', type: 'date', required: true },
            { name: 'replaced_date', label: 'Replaced Date', type: 'date' },
            { name: 'sex', label: 'Sex', type: 'select', options: ['M', 'F'], required: true },
            { name: 'height', label: 'Height', placeholder: "5'-09\"" },
            { name: 'dl_class', label: 'Class', placeholder: 'E' },
            { name: 'restrictions', label: 'Restrictions', placeholder: 'NONE' },
            { name: 'endorsements', label: 'Endorsements', placeholder: 'NONE' },
            { name: 'dd_code', label: 'DD Code' },
            { name: 'security_text', label: 'Security Text' },
            { name: 'back_top_serial', label: 'Back Top Serial' },
            { name: 'back_vertical_serial', label: 'Back Vertical Serial' }
        ],
        buildPayload: (data, photoBase64, apiKey) => ({
            api_key: apiKey,
            template_id: 914,
            output_style: "photo",
            data: {
                first_name: data.first_name || '',
                last_name: data.last_name || '',
                license_number: data.license_number || '',
                address_street: data.address_street || '',
                address_city: data.address_city || '',
                address_state: data.address_state || '',
                address_zip: data.address_zip || '',
                date_of_birth: data.date_of_birth || '',
                issue_date: data.issue_date || '',
                expire_date: data.expire_date || '',
                replaced_date: data.replaced_date || '',
                sex: data.sex || '',
                height: data.height || '',
                dl_class: data.dl_class || '',
                restrictions: data.restrictions || '',
                endorsements: data.endorsements || '',
                dd_code: data.dd_code || '',
                security_text: data.security_text || '',
                security_text: data.security_text || '',
                security_text: data.security_text || '',
                security_text: data.security_text || '',
                back_top_serial: data.back_top_serial || '',
                back_vertical_serial: data.back_vertical_serial || '',
                main_photo: photoBase64,
                main_photo: photoBase64,
                main_photo: photoBase64,
                main_photo: photoBase64
            }
        })
    }
};

module.exports = STATES;
